### ISSUE TITLE
[EPIC] Build a searchable standalone directory of public books across many Pressbooks networks

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#208]
This task has several components. 
**Phase 1:**
- [x] [Move data collectors to main PB repo](https://github.com/pressbooks/pressbooks/issues/1795)
- [x] [Improve speed/performance of the v2 API for books](https://github.com/pressbooks/pressbooks/issues/1795)
- [x] [Write spec for website displaying a catalogue of public Pressbooks across many networks](https://github.com/pressbooks/pressbooks/issues/1798)

**Phase 2:** 
- [x] Select database & data architecture for storing JSON statements (Algolia?)
- [x] [Collect JSON statements from several networks and store in database](pressbooks/ideas#265)

**Phase 3:** 
- [x] grab representative amount of records (at least 500 total from 6 separate networks) and make sure we're getting all public books. Improve the fetcher (hopefully just include the parameter, if not, improve the API) to make sure that we're getting all records) - L https://github.com/pressbooks/book-directory-fetcher/issues/2
- [x] edit fetcher so that json is transformed to match full set of info possibly provided by API - M https://github.com/pressbooks/book-directory-fetcher/issues/1
- [x] set up cron job to ensure we're getting incremental changes/updates - M https://github.com/pressbooks/book-directory-fetcher/issues/3
- [x] build very basic front end w/ instant search & validate that it works - M https://github.com/pressbooks/book-directory-fetcher/issues/4
- [x] Refine & further spec front end wireframe - L https://github.com/pressbooks/book-directory-fetcher/issues/7
- [x] Research/choose method for remove books from directory when they're deleted/moved/made private - M: https://github.com/pressbooks/book-directory-fetcher/issues/8
- [x] Notify directory fetcher when relevant book info is changed - https://github.com/pressbooks/pressbooks/issues/1905
- [x] Build fetcher endpoint to receive calls/status update notifications from networks - https://github.com/pressbooks/book-directory-fetcher/issues/9

**Phase 4:**
- [x] set up deployment pipeline in AWS (test & automatically deploy changes to Lambda-based fetcher) - L https://github.com/pressbooks/book-directory-fetcher/issues/5
- [x] Get v3 API spec ready; i.e. identify desired changes for API & data model; refine https://github.com/pressbooks/pressbooks/issues/1797 as needed - M
- [x] Finalize [front end spec]((https://docs.google.com/document/d/1DIHAuew1nyGErLExtHfj2rNcInvVX_scJ2DHJwzORns/edit#heading=h.qr91vyvla24r)) for book cards & filtering/searching capabilities https://github.com/pressbooks/book-directory-fetcher/issues/14 - L
- [x] [Improve API](https://github.com/pressbooks/pressbooks/issues/1797) and Algolia storage based on needs identified in spec - L

**Phase 5 (web app front end):**
- [x] Connect app to front end repo w/ Algolia boilerplate: https://github.com/pressbooks/pressbooks-directory/issues/1 - M
- [x] Set up a vue.js app to AWS using staging.pressbooks.directory (staging) and pressbooks.directory (prod) https://github.com/pressbooks/pressbooks-book-directory-fe/issues/2 - XL
- [x] Build v1 of individual book card view -- cover, title, metadata etc (without filter actions) using flexbox https://github.com/pressbooks/pressbooks-directory/issues/3 - XL
- [x] Build v1 of desired filters/facets from existing vue.js library & spec https://github.com/pressbooks/pressbooks-book-directory-fe/issues/4 - L
- [x] Improve field type info when we post to Algolia: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/7 - M
- [x] improve consistency of data stored in Algolia: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/8 - M
- [x] Produce spec/wireframes for site, facets, search: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/10 - L
- [x] Build site, facets, search to spec: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/12 - L
- [x] Produce spec/wireframes for cards: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/5 - L
- [x] Build cards to spec: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/11 - L
- [x] Use a11y linter: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/9 - M
- [x] 'last updated' improvement: https://github.com/pressbooks/pressbooks/issues/1962 - S

**Phase 6 (pre-public unveiling)**
- [x] UX/UI review - L https://github.com/pressbooks/pressbooks-book-directory-fe/issues/21
- [x] Enable E2E testing for deployment pipeline - https://github.com/pressbooks/pressbooks-book-directory-fe/issues/44 - M
- [x] Round one of user feedback & assorted aesthetic improvements/tweaks for overall UX/UI (new task)
- [x] Add open source networks to fetcher - https://github.com/pressbooks/book-directory-fetcher/issues/24 - M
- [x] review existing records & make decision about need for moderation

**Phase 7** 
- [x] SEO optimization for directory
- [ ] Research task for users/collections: https://github.com/pressbooks/pb-directory/issues/43
- [ ] Allow users to create accounts & make collections: https://github.com/pressbooks/pb-directory/issues/42

**Comment by SteelWagstaff** [comment]
This task has several components. Phase 1 to include: 
* Pressbooks/Pressbooks#1795 
* Pressbooks/Pressbooks#1796 
* Pressbooks/Pressbooks#1797 
* Pressbooks/Pressbooks#1798

**Comment by SteelWagstaff** [comment]
NEXT STEPS:

- [ ] grab representative amount of records and make sure we're getting all public books [at least 100 from X amount of networks]
- [ ] improve the fetcher / API to make sure that we're getting enough records & that we're getting incremental changes/updates
- [ ] build very basic front end w/ instant search & validate that it works
- [ ] set up deployment pipeline in AWS (Lambda-based fetcher & front end, will use when this becomes a web app) 
- [ ] check on endpoint querying for books to make sure all desired metadata is included; if not, update API (v3, based on spec needs)

**Comment by SteelWagstaff** [comment]
set up cron job to ensure we're getting incremental changes/updates - M
- [ ] build very basic front end w/ instant search & validate that it works - M

- [ ] set up deployment pipeline in AWS (test & automatically deploy changes to Lambda-based fetcher) - L
- [ ] set up deployment pipline for front end (including Browser Stack test), will use when this becomes a web app
