### ISSUE TITLE
Bundle of footnote issues

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#290]
- [ ] Improve underlying HTML for accessibility: https://github.com/pressbooks/pressbooks-book/issues/664
- [x] Covert footnotes in parts to endnotes just like is the case with chapters: https://github.com/pressbooks/pressbooks-book/issues/610
- [x] Fix endnote float issue: https://github.com/pressbooks/pressbooks-book/issues/626
- [x] Fix footnote margin issue in PDF exports: https://github.com/pressbooks/pressbooks-book/issues/587
- [x] Fix word import sanitization issue affecting footnotes: https://github.com/pressbooks/pressbooks/issues/1852
- [x] Fix auto URL parsing issue with footnotes: https://github.com/pressbooks/pressbooks-book/issues/578
- [x] Research inline/block issues with footnotes & pdf exports: https://github.com/pressbooks/pressbooks/issues/1831

**Comment by ricardopressbooks** [comment]
It happens with **baker** theme.

**Comment by ricardopressbooks** [comment]
After discuss with @SteelWagstaff :
scope for: 

> Fix word import sanitization issue affecting footnotes: pressbooks/pressbooks#1852

Now, footnotes imported from .docx are not imported at all. So I'll fix it and add italics style if needed. **Add footnotes shortcode will be considered and estimated in the future**.
