### ISSUE TITLE
[Epic] Improve & document QA & CI/CD processes 

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#312]
# QA/testing
- [ ] Review dependabot rules & explore automerge to dev: https://github.com/pressbooks/private/issues/162
- [x] Autodeploy dev commits to integrations/textopress for testing & review:  https://github.com/pressbooks/private/issues/165
- [ ] Autobump 3rd party plugin updates on integrations/textopress for testing & review: https://github.com/pressbooks/private/issues/166
- [ ] Attempt to incorporate test suites for 3rd party plugins into our pipeline: https://github.com/pressbooks/private/issues/161
- [x] Explore automated visual regression testing https://github.com/pressbooks/ideas/issues/311

# CI/CD
- [x] Explore use of Sentry.IO with pressbooks/pressbooks: https://github.com/pressbooks/private/issues/130
- [ ] Explore use of Teamcity for local pipeline simulations: https://github.com/pressbooks/private/issues/164
- [ ] Explore use of PHPCS (PHP_CodeSniffer rules for security) with one repo: https://github.com/pressbooks/private/issues/163
- [x] Explore use of a11y linting tools with Pressbooks Directory front end project: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/9
- [x] Explore use of GitHub Actions in place of Travis for building/deploying repos: https://github.com/pressbooks/pressbooks-bisac/issues/7 + https://github.com/pressbooks/pressbooks/pull/2103

# Packaging/deploy
- [ ] Explore Transifex/GitHub integration for automatic translation updates https://github.com/pressbooks/ideas/issues/283
- [ ] Automate initial production of release notes https://github.com/pressbooks/private/issues/167
- [ ] Reassassess packing & deploy processes for all repos https://github.com/pressbooks/private/issues/23
