### ISSUE TITLE
Gather 1st round of user feedback & build aesthetic improvements for overall UX/UI

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#322]
Steel has sent feedback form out to several PB colleagues: https://docs.google.com/forms/d/1nLuUsxO6k9Y5x4Zh53Hd0FYCBottJjdGs-lRVZlHbA8/edit and requested responses by Monday.

- [x] Add clear refinements button: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/54
- [x] Allow visitors to change cards per page: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/56
- [x] Add 'Search' button to main directory search & institute a 3 second debounce: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/47
- [ ] Add clear options for numeric facets: https://github.com/pressbooks/pressbooks-book-directory-fe/issues/57
- [ ] Add voice search option for main search: https://github.com/pressbooks/pb-directory/issues/44

**Comment by SteelWagstaff** [comment]
User feedback has been summarized in https://docs.google.com/document/d/170TmnKUBZo4PxmESyUybi1IxZets8g3XCjeP6dBw0NE/edit?ouid=102406216832199618062&usp=docs_home&ths=true
