### ISSUE TITLE
Stop tracking visits from logged in administrators and editors in Google Analytics

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#81]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [X] Integration with third-party services

### Feature Description

To not track administrators and editors and ... from google analitics

### Feature Use Case

We have dozens of authors, they open hundreds of pages day. As each author is from one place, is complicate to avoid their hits. The resoult we have too many fake views.

### Other Notes

https://www.webhostinghero.com/how-to-avoid-logged-in-user-tracking-with-google-analytics-in-wordpress/

**Comment by SteelWagstaff** [comment]
@colomet you can do this yourself with a plugin or Google Analytics filter. See https://www.monsterinsights.com/how-to-stop-google-analytics-from-tracking-logged-in-users-in-wordpress/. Closing as it's not a Pressbooks issue.
